#@package _global_
defaults:
  - /mephisto/blueprint: remote_procedure
  - /mephisto/architect: local
  - /mephisto/provider: mock
mephisto:
  blueprint:
    task_source: ${task_dir}/webapp/build/bundle.js
    link_task_source: false
    # NOTE pick something based on your task
    block_qualification: fantasy_gameplay_block
    units_per_assignment: 1
  task:
    allowed_concurrent: 1
    task_name: light-gameplay-task
    task_title: "Pretend to be a character in a fantasy text-adventure world"
    task_description: >
      You will be provided a character to play as in a text adventure game.
      After a brief tutorial, you can navigate the world and interact with other players in the world.
      Try to stay in character and accomplish your goal.
    # NOTE set a reasonable reward
    task_reward: 4.00
    task_tags: "fantasy,text,role-playing,adventure,dialogue"
